name: flutter_crystalline
description: Crystal clear state management
version: 0.7.0
homepage: https://github.com/easazade/crystalline

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=3.10.4"

dependencies:
  flutter:
    sdk: flutter
  crystalline: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

