name: crystalline_builder
description: builder for crystalline
repository: https://github.com/easazade/crystalline
version: 0.7.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  crystalline: ^0.7.0
  flutter_crystalline: ^0.7.0
  build: ">=3.0.0 <5.0.0"
  analyzer: '>=9.0.0 <11.0.0'
  source_gen: ">=3.0.0 <5.0.0"
  dart_style: ^3.1.1
  glob: ^2.1.2
  recase: ^4.1.0
  collection: ^1.19.1

dev_dependencies:
  build_runner: ^2.6.0
  lints: ^6.1.0
  test: ^1.24.0
