name: crystalline
description: Crystal clear state management
version: 0.6.0
repository: https://github.com/easazade/crystalline

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  meta: ^1.9.1
  collection: ^1.18.0

dev_dependencies:
  test: ^1.21.0
  lints: ^6.0.0
